//
// Generated with FrostbiteGen by Chod
// File: SDK\AutoGeneratedBundle.h
// Created: Wed Mar 10 19:08:34 2021
//

#ifndef FBGEN_AutoGeneratedBundle_H
#define FBGEN_AutoGeneratedBundle_H

#include "BlueprintBundleReference.h"
struct AutoGeneratedBundle
{
	static void* GetTypeInfo()
	{
		return (void*)0x0000000142816100;
	}
	BlueprintBundleReference m_BlueprintBundleReference; // 0x0
}; // size = 0x38

#endif // FBGEN_AutoGeneratedBundle_H
