//
// Generated with FrostbiteGen by Chod
// File: SDK\UIInputAction.h
// Created: Wed Mar 10 18:59:54 2021
//

#ifndef FBGEN_UIInputAction_H
#define FBGEN_UIInputAction_H

enum UIInputAction
{
	UIInputAction_NavigateUp = 0x0,
	UIInputAction_NavigateDown = 0x1,
	UIInputAction_NavigateLeft = 0x2,
	UIInputAction_NavigateRight = 0x3,
	UIInputAction_TabLeft = 0x4,
	UIInputAction_TabRight = 0x5,
	UIInputAction_Activate = 0x6,
	UIInputAction_Deactivate = 0x7,
	UIInputAction_Menu = 0x8,
	UIInputAction_Cancel = 0x9,
	UIInputAction_OK = 0xa,
	UIInputAction_Back = 0xb,
	UIInputAction_Tab = 0xc,
	UIInputAction_Edit = 0xd,
	UIInputAction_View = 0xe,
	UIInputAction_LThumb = 0xf,
	UIInputAction_RThumb = 0x10,
	UIInputAction_MapZoom = 0x11,
	UIInputAction_MapSize = 0x12,
	UIInputAction_SayAllChat = 0x13,
	UIInputAction_TeamChat = 0x14,
	UIInputAction_SquadChat = 0x15,
	UIInputAction_CommoRose = 0x16,
	UIInputAction_ToggleChat = 0x17,
	UIInputAction_ToggleMinimapType = 0x18,
	UIInputAction_DigitalUp = 0x19,
	UIInputAction_DigitalDown = 0x1a,
	UIInputAction_DigitalLeft = 0x1b,
	UIInputAction_DigitalRight = 0x1c,
	UIInputAction_NavigateRUp = 0x1d,
	UIInputAction_NavigateRDown = 0x1e,
	UIInputAction_NavigateRLeft = 0x1f,
	UIInputAction_NavigateRRight = 0x20,
	UIInputAction_MenuTriggerLeft = 0x21,
	UIInputAction_MenuTriggerRight = 0x22,
	UIInputAction_TacticalMenu = 0x23,
	UIInputAction_ConversationSelect = 0x24,
	UIInputAction_ConversationSkip = 0x25,
	UIInputAction_ConversationChangeSelection = 0x26,
	UIInputAction_BattledashToggle = 0x27,
	UIInputAction_VoipPushToTalk = 0x28,
	UIInputAction_MultipleSelect = 0x29,
	UIInputAction_SpectatorViewPrev = 0x2a,
	UIInputAction_SpectatorViewNext = 0x2b,
	UIInputAction_SpectatorTargetPrev = 0x2c,
	UIInputAction_SpectatorTargetNext = 0x2d,
	UIInputAction_SpectatorViewTableTop = 0x2e,
	UIInputAction_SpectatorViewFirstPerson = 0x2f,
	UIInputAction_SpectatorViewThirdPerson = 0x30,
	UIInputAction_SpectatorViewFreeCam = 0x31,
	UIInputAction_SpectatorViewPlayer1 = 0x32,
	UIInputAction_SpectatorViewPlayer2 = 0x33,
	UIInputAction_SpectatorViewPlayer3 = 0x34,
	UIInputAction_SpectatorViewPlayer4 = 0x35,
	UIInputAction_SpectatorViewPlayer5 = 0x36,
	UIInputAction_SpectatorViewPlayer6 = 0x37,
	UIInputAction_SpectatorViewPlayer7 = 0x38,
	UIInputAction_SpectatorViewPlayer8 = 0x39,
	UIInputAction_SpectatorViewPlayer9 = 0x3a,
	UIInputAction_SpectatorViewPlayer10 = 0x3b,
	UIInputAction_SpectatorViewPlayer11 = 0x3c,
	UIInputAction_SpectatorViewPlayer12 = 0x3d,
	UIInputAction_SpectatorViewPlayer13 = 0x3e,
	UIInputAction_SpectatorViewPlayer14 = 0x3f,
	UIInputAction_SpectatorViewPlayer15 = 0x40,
	UIInputAction_SpectatorViewPlayer16 = 0x41,
	UIInputAction_SpectatorViewOptions = 0x42,
	UIInputAction_SpectatorHudVisibility = 0x43,
	UIInputAction_SpectatorTargetPrevInSquad = 0x44,
	UIInputAction_SpectatorTargetNextInSquad = 0x45,
	UIInputAction_SpectatorTargetPrevOnTeam = 0x46,
	UIInputAction_SpectatorTargetNextOnTeam = 0x47,
	UIInputAction_SpectatorSquadLeft = 0x48,
	UIInputAction_SpectatorSquadRight = 0x49,
	UIInputAction_SpectatorSquadUp = 0x4a,
	UIInputAction_SpectatorSquadDown = 0x4b,
	UIInputAction_SpectatorSquadActivate = 0x4c,
	UIInputAction_Start = 0x4d,
	UIInputAction_Minimize = 0x4e,
	UIInputAction_SelectAll = 0x4f,
	UIInputAction_Skip = 0x50,
	UIInputAction_ToggleScoreboard = 0x51,
	UIInputAction_Size = 0x52,
	UIInputAction_None = 0x53,
};

#endif // FBGEN_UIInputAction_H
