//
// Generated with FrostbiteGen by Chod
// File: SDK\VertexElementUsage.h
// Created: Wed Mar 10 18:59:16 2021
//

#ifndef FBGEN_VertexElementUsage_H
#define FBGEN_VertexElementUsage_H

enum VertexElementUsage
{
	VertexElementUsage_Unknown = 0x0,
	VertexElementUsage_Pos = 0x1,
	VertexElementUsage_BoneIndices = 0x2,
	VertexElementUsage_BoneIndices2 = 0x3,
	VertexElementUsage_BoneWeights = 0x4,
	VertexElementUsage_BoneWeights2 = 0x5,
	VertexElementUsage_Normal = 0x6,
	VertexElementUsage_Tangent = 0x7,
	VertexElementUsage_Binormal = 0x8,
	VertexElementUsage_BinormalSign = 0x9,
	VertexElementUsage_WorldTrans1 = 0xa,
	VertexElementUsage_WorldTrans2 = 0xb,
	VertexElementUsage_WorldTrans3 = 0xc,
	VertexElementUsage_InstanceId = 0xd,
	VertexElementUsage_InstanceUserData0 = 0xe,
	VertexElementUsage_PrevInstanceUserData0 = 0xf,
	VertexElementUsage_InstanceUserData1 = 0x10,
	VertexElementUsage_PrevWorldTrans1 = 0x11,
	VertexElementUsage_PrevWorldTrans2 = 0x12,
	VertexElementUsage_PrevWorldTrans3 = 0x13,
	VertexElementUsage_XenonIndex = 0x14,
	VertexElementUsage_XenonBarycentric = 0x15,
	VertexElementUsage_XenonQuadID = 0x16,
	VertexElementUsage_Index = 0x17,
	VertexElementUsage_ViewIndex = 0x18,
	VertexElementUsage_Color0 = 0x1e,
	VertexElementUsage_Color1 = 0x1f,
	VertexElementUsage_TexCoord0 = 0x21,
	VertexElementUsage_TexCoord1 = 0x22,
	VertexElementUsage_TexCoord2 = 0x23,
	VertexElementUsage_TexCoord3 = 0x24,
	VertexElementUsage_TexCoord4 = 0x25,
	VertexElementUsage_TexCoord5 = 0x26,
	VertexElementUsage_TexCoord6 = 0x27,
	VertexElementUsage_TexCoord7 = 0x28,
	VertexElementUsage_DisplacementMapTexCoord = 0x29,
	VertexElementUsage_RadiosityTexCoord = 0x2a,
	VertexElementUsage_VisInfo = 0x2b,
	VertexElementUsage_SpriteSize = 0x2c,
	VertexElementUsage_PackedTexCoord0 = 0x2d,
	VertexElementUsage_PackedTexCoord1 = 0x2e,
	VertexElementUsage_PackedTexCoord2 = 0x2f,
	VertexElementUsage_PackedTexCoord3 = 0x30,
	VertexElementUsage_ClipDistance0 = 0x31,
	VertexElementUsage_ClipDistance1 = 0x32,
	VertexElementUsage_SubMaterialIndex = 0x33,
	VertexElementUsage_TangentSpace = 0x34,
	VertexElementUsage_CrowdPackedNormalSign = 0x35,
	VertexElementUsage_CrowdPackedTangentSpaceSigns = 0x36,
	VertexElementUsage_CrowdPackedNormal = 0x37,
	VertexElementUsage_BranchInfo = 0x3c,
	VertexElementUsage_PosAndScale = 0x3d,
	VertexElementUsage_Rotation = 0x3e,
	VertexElementUsage_SpriteSizeAndUv = 0x3f,
	VertexElementUsage_FadePos = 0x5a,
	VertexElementUsage_SpawnTime = 0x5b,
	VertexElementUsage_PosAndSoftMul = 0x96,
	VertexElementUsage_Alpha = 0x97,
	VertexElementUsage_Misc0 = 0x98,
	VertexElementUsage_Misc1 = 0x99,
	VertexElementUsage_Misc2 = 0x9a,
	VertexElementUsage_Misc3 = 0x9b,
	VertexElementUsage_LeftAndRotation = 0x9c,
	VertexElementUsage_UpAndNormalBlend = 0x9d,
	VertexElementUsage_Hl2BasisL0 = 0x9e,
	VertexElementUsage_Hl2BasisL1 = 0x9f,
	VertexElementUsage_Hl2BasisL2 = 0xa0,
	VertexElementUsage_PosAndRejectCulling = 0xa1,
	VertexElementUsage_Shadow = 0xa2,
	VertexElementUsage_CustomParams = 0xa3,
	VertexElementUsage_PatchUv = 0xb4,
	VertexElementUsage_Height = 0xb5,
	VertexElementUsage_MaskUVs0 = 0xb6,
	VertexElementUsage_MaskUVs1 = 0xb7,
	VertexElementUsage_MaskUVs2 = 0xb8,
	VertexElementUsage_MaskUVs3 = 0xb9,
	VertexElementUsage_UserMasks = 0xba,
	VertexElementUsage_HeightfieldUv = 0xbb,
	VertexElementUsage_MaskUv = 0xbc,
	VertexElementUsage_GlobalColorUv = 0xbd,
	VertexElementUsage_HeightfieldPixelSizeAndAspect = 0xbe,
	VertexElementUsage_WorldPositionXz = 0xbf,
	VertexElementUsage_TerrainTextureNodeUv = 0xc0,
	VertexElementUsage_ParentTerrainTextureNodeUv = 0xc1,
	VertexElementUsage_DeformationIndex = 0xcd,
	VertexElementUsage_DeformationWeight = 0xce,
	VertexElementUsage_DeformationPosition = 0xcf,
	VertexElementUsage_Delta = 0xd0,
	VertexElementUsage_ElementIndex = 0xd1,
	VertexElementUsage_Uv01 = 0xd2,
	VertexElementUsage_WorldPos = 0xd3,
	VertexElementUsage_EyeVector = 0xd4,
	VertexElementUsage_LightParams1 = 0xdc,
	VertexElementUsage_LightParams2 = 0xdd,
	VertexElementUsage_LightSubParams = 0xde,
	VertexElementUsage_LightSideVector = 0xdf,
	VertexElementUsage_LightInnerAndOuterAngle = 0xe0,
	VertexElementUsage_LightDir = 0xe1,
	VertexElementUsage_LightMatrix1 = 0xe2,
	VertexElementUsage_LightMatrix2 = 0xe3,
	VertexElementUsage_LightMatrix3 = 0xe4,
	VertexElementUsage_LightMatrix4 = 0xe5,
	VertexElementUsage_Custom = 0xe6,
	VertexElementUsage_DestructionMaskDistance = 0xf0,
	VertexElementUsage_DestructionMaskTexCoord = 0xf1,
};

#endif // FBGEN_VertexElementUsage_H
