//
// Generated with FrostbiteGen by Chod
// File: SDK\WorldViewMode.h
// Created: Wed Mar 10 18:58:43 2021
//

#ifndef FBGEN_WorldViewMode_H
#define FBGEN_WorldViewMode_H

enum WorldViewMode
{
	WorldViewMode_Default = 0x0,
	WorldViewMode_Diffuse = 0x1,
	WorldViewMode_BaseColor = 0x2,
	WorldViewMode_MetalMask = 0x3,
	WorldViewMode_Reflectance = 0x4,
	WorldViewMode_Specular = 0x5,
	WorldViewMode_Fresnel0 = 0x6,
	WorldViewMode_Fresnel90 = 0x7,
	WorldViewMode_Normal = 0x8,
	WorldViewMode_Smoothness = 0x9,
	WorldViewMode_Roughness = 0xa,
	WorldViewMode_LinearRoughness = 0xb,
	WorldViewMode_MaterialId = 0xc,
	WorldViewMode_MaterialIdTileMask = 0xd,
	WorldViewMode_SubSurfaceProfileId = 0xe,
	WorldViewMode_SubSurfaceRadius = 0xf,
	WorldViewMode_SubSurfaceTranslucency = 0x10,
	WorldViewMode_HairTangent = 0x11,
	WorldViewMode_HairVelocity = 0x12,
	WorldViewMode_HairTangentShift = 0x13,
	WorldViewMode_HairOcclusion = 0x14,
	WorldViewMode_HairCoverageX = 0x15,
	WorldViewMode_HairCoverageY = 0x16,
	WorldViewMode_Thickness = 0x17,
	WorldViewMode_LargeThickness = 0x18,
	WorldViewMode_CustomEnvmapId = 0x19,
	WorldViewMode_CoatCoverage = 0x1a,
	WorldViewMode_MaterialData = 0x1b,
	WorldViewMode_RawLinear = 0x1c,
	WorldViewMode_RawLinearAlpha = 0x1d,
	WorldViewMode_Light = 0x1e,
	WorldViewMode_LightDiffuse = 0x1f,
	WorldViewMode_LightColoredDiffuse = 0x20,
	WorldViewMode_LightSpecular = 0x21,
	WorldViewMode_LightIndirectDiffuse = 0x22,
	WorldViewMode_LightColoredIndirectDiffuse = 0x23,
	WorldViewMode_LightTranslucency = 0x24,
	WorldViewMode_LightReflectionOnly = 0x25,
	WorldViewMode_LightMirrorReflectionOnly = 0x26,
	WorldViewMode_ShadowMask = 0x27,
	WorldViewMode_Transmittance = 0x28,
	WorldViewMode_SkyVisibility = 0x29,
	WorldViewMode_Emissive = 0x2a,
	WorldViewMode_DynamicAO = 0x2b,
	WorldViewMode_Depth = 0x2c,
	WorldViewMode_RadiosityLightMaps = 0x2d,
	WorldViewMode_RadiosityDiffuseColor = 0x2e,
	WorldViewMode_RadiosityTargetUV = 0x2f,
	WorldViewMode_Overdraw = 0x30,
	WorldViewMode_OverdrawDepthTest = 0x31,
	WorldViewMode_LightOverdraw = 0x32,
	WorldViewMode_ShaderCost = 0x33,
	WorldViewMode_Occluders = 0x34,
	WorldViewMode_SssTiles = 0x35,
	WorldViewMode_DiffuseRange = 0x36,
	WorldViewMode_Fresnel0Range = 0x37,
	WorldViewMode_IlluminanceRange = 0x38,
	WorldViewMode_FilmicEffects = 0x39,
	WorldViewMode_CoC = 0x3a,
	WorldViewMode_VelocityVector = 0x3b,
	WorldViewMode_DistortionVector = 0x3c,
	WorldViewMode_StaticIBL = 0x3d,
	WorldViewMode_ScreenSpaceRaytraceReflections = 0x3e,
	WorldViewMode_ScreenSpaceRaytraceCoverage = 0x3f,
	WorldViewMode_ScreenSpaceRaytraceImportons = 0x40,
	WorldViewMode_Count = 0x41,
};

#endif // FBGEN_WorldViewMode_H
